// DATA
export const DATA = 'DATA'
// EXERCICE
export const EXERCICE = 'EXERCICE'
export const EXERCICE_RUNNING = 'EXERCICE_RUNNING'
export const EXERCICE_WORKOUT = 'EXERCICE_WORKOUT'
// PROGRESS
export const PROGRESS_TODO = 'TODO'
export const PROGRESS_ONGOING = 'ONGOING'
export const PROGRESS_PAUSED = 'PAUSED'
export const PROGRESS_ABORTED = 'ABORTED'
export const PROGRESS_DONE = 'DONE'
// STRUCTURE
export const STRUCTURE = 'STRUCTURE'
export const STRUCTURE_SERIE = 'STRUCTURE_SERIE'
export const STRUCTURE_SESSION = 'STRUCTURE_SESSION'
export const STRUCTURE_ROTATION = 'STRUCTURE_ROTATION'
// TEMPLATE
export const TEMPLATE = 'TEMPLATE'
