// EXERCICE
export const EXERCICE_ADD = 'EXERCICE_ADD';
export const EXERCICE_REST = 'EXERCICE_REST';
export const EXERCICE_START = 'EXERCICE_START';
export const EXERCICE_STOP = 'EXERCICE_STOP';
export const EXERCICE_UPDATE = 'EXERCICE_UPDATE';
// SELECTED
export const SELECTED_SELECT = 'SELECTED_SELECT';
// STRUCTURE
export const STRUCTURE_ADD = 'STRUCTURE_ADD';
export const STRUCTURE_REST = 'STRUCTURE_REST';
export const STRUCTURE_START = 'STRUCTURE_START';
export const STRUCTURE_STOP = 'STRUCTURE_STOP';
export const STRUCTURE_UPDATE = 'STRUCTURE_UPDATE';
