// EXERCICE
export const EXERCICE = 'EXERCICE'
export const EXERCICE_RUNNING = 'EXERCICE_RUNNING'
export const EXERCICE_WORKOUT = 'EXERCICE_WORKOUT'
// STRUCTURE
export const STRUCTURE = 'STRUCTURE'
export const STRUCTURE_SERIE = 'STRUCTURE_SERIE'
export const STRUCTURE_SESSION = 'STRUCTURE_SESSION'
export const STRUCTURE_ROTATION = 'STRUCTURE_ROTATION'
// PROGRESS
export const TODO = 'TODO'
export const ONGOING = 'ONGOING'
export const PAUSED = 'PAUSED'
export const ABORTED = 'ABORTED'
export const DONE = 'DONE'
